name: Tag and Release Module
on:
  pull_request:
    types: [closed]
jobs:
  tag-and-release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 0.0.0
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: 'Get next version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}
      - uses: softprops/action-gh-release@v2
        if: contains(github.event.pull_request.labels.*.name, 'minor')
        with:
          generate_release_notes: true
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag_name: "${{ steps.semvers.outputs.v_minor }}"
      - uses: softprops/action-gh-release@v2
        if: contains(github.event.pull_request.labels.*.name, 'major')
        with:
          generate_release_notes: true
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag_name: "${{ steps.semvers.outputs.v_major }}"
      - uses: softprops/action-gh-release@v2
        if: contains(github.event.pull_request.labels.*.name, 'patch')
        with:
          generate_release_notes: true
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag_name: "${{ steps.semvers.outputs.v_patch }}"
